import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import Script from "next/script";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "google-adsense-account": "ca-pub-1361802956304203",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta name="google-adsense-account" content="ca-pub-1361802956304203" />
      </head>

      <body className="min-h-full flex flex-col">
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-VHL8Y6LYN0"
          strategy="afterInteractive"
        />

        <Script id="google-analytics" strategy="afterInteractive">
          {`
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-VHL8Y6LYN0');
    `}
        </Script>

        <Script
          async
          strategy="afterInteractive"
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1361802956304203"
          crossOrigin="anonymous"
        />
        <ReduxProvider>
          <header className="w-full bg-white dark:bg-zinc-900 border-b border-zinc-200 dark:border-zinc-800">
            <div className="max-w-7xl mx-auto px-4 py-3 flex items-center gap-6">
              <Link href="/" className="font-semibold text-lg">
                Home
              </Link>
              <nav className="flex items-center gap-4">
                <Link
                  href="/about"
                  className="text-sm text-zinc-700 dark:text-zinc-300"
                >
                  About
                </Link>
                <Link
                  href="/contact"
                  className="text-sm text-zinc-700 dark:text-zinc-300"
                >
                  Contact
                </Link>
                <Link
                  href="/privacy"
                  className="text-sm text-zinc-700 dark:text-zinc-300"
                >
                  Privacy
                </Link>
                <Link
                  href="/terms"
                  className="text-sm text-zinc-700 dark:text-zinc-300"
                >
                  Terms
                </Link>
              </nav>
            </div>
          </header>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
